version: "3.5"
services:
  mongodb:
    container_name: accounting-booking-software-backend
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
